### ISSUE TITLE
add rust-toolchain file

### ISSUE THREAD

**Issue by mike-kfed** [HKalbasi/rust-arduino-generator#1]
Thanks for the easy to use template! How do you feel about adding a file called `rust-toolchain` with content
```
[toolchain]
channel = "nightly-2021-01-07"
components = ["rust-src"]
```
afterwards simply running `cargo build` does the trick, and it would help with the current Rahix/avr-hal#124 issue (and generally down the line as AVR support will stay nightly for long)

**Comment by hkalbasi** [comment]
Thank you for this tip! Is it know OK?

**Comment by mike-kfed** [comment]
the file needs to be called `rust-toolchain` not `rust-toolchain.toml`

once the rename is done this issue can be considered fixed, thanks!

**Comment by hkalbasi** [comment]
I thought it is ok to use `.toml` when I see https://github.com/rust-lang/rustup/pull/2653 merged

But it is too new :(
